// Generated GRPC code for FlatBuffers swift!
/// The following code is generated by the Flatbuffers library which might not be in sync with grpc-swift
/// in case of an issue please open github issue, though it would be maintained

// swiftlint:disable all
// swiftformat:disable all

#if !os(Windows)
import FlatBuffers
import Foundation
import GRPCCore


/// Usage: instantiate MyGame.Example.MonsterStorageServiceClient, then call methods of this protocol to make API calls.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension FlatBuffersMessageSerializer: MessageSerializer {
  public func serialize<Bytes>(_ message: Message) throws -> Bytes where Bytes : GRPCCore.GRPCContiguousBytes {
    do {
      return try self.serialize(message: message) as! Bytes
    } catch let error {
      throw RPCError(
        code: .invalidArgument,
        message: "Can't serialize message",
        cause: error
      )
    }
  }
}

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension FlatBuffersMessageDeserializer: MessageDeserializer {
  public func deserialize<Bytes>(_ serializedMessageBytes: Bytes) throws -> Message where Bytes : GRPCCore.GRPCContiguousBytes {
    do {
      return try serializedMessageBytes.withUnsafeBytes {
        try self.deserialize(pointer: $0)
      }
    } catch let error {
      throw RPCError(
        code: .invalidArgument,
        message: "Can't Decode message of type \(Message.self)",
        cause: error
      )
    }
  }
}
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
public enum MyGame_Example_MonsterStorage: Sendable {
  public static let descriptor = GRPCCore.ServiceDescriptor(fullyQualifiedService: "MyGame.Example.MonsterStorage")
  public enum Method: Sendable {
    public enum Store: Sendable {
      public typealias Input = FlatBufferBuilder
      public typealias Output = MyGame_Example_Stat
      public static let descriptor = GRPCCore.MethodDescriptor(
        service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "MyGame.Example.MonsterStorage"),
        method: "Store"
      )
    }
    public enum Retrieve: Sendable {
      public typealias Input = FlatBufferBuilder
      public typealias Output = MyGame_Example_Monster
      public static let descriptor = GRPCCore.MethodDescriptor(
        service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "MyGame.Example.MonsterStorage"),
        method: "Retrieve"
      )
    }
    public enum GetMaxHitPoint: Sendable {
      public typealias Input = FlatBufferBuilder
      public typealias Output = MyGame_Example_Stat
      public static let descriptor = GRPCCore.MethodDescriptor(
        service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "MyGame.Example.MonsterStorage"),
        method: "GetMaxHitPoint"
      )
    }
    public enum GetMinMaxHitPoints: Sendable {
      public typealias Input = FlatBufferBuilder
      public typealias Output = MyGame_Example_Stat
      public static let descriptor = GRPCCore.MethodDescriptor(
        service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "MyGame.Example.MonsterStorage"),
        method: "GetMinMaxHitPoints"
      )
    }
    public static let descriptors: [GRPCCore.MethodDescriptor] = [
      Store.descriptor,
      Retrieve.descriptor,
      GetMaxHitPoint.descriptor,
      GetMinMaxHitPoints.descriptor,
    ]
  }
}

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension GRPCCore.ServiceDescriptor {
  public static let MyGame_Example_MonsterStorage = GRPCCore.ServiceDescriptor(fullyQualifiedService: "MyGame.Example.MonsterStorage")
}

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension MyGame_Example_MonsterStorage {
  public protocol StreamingServiceProtocol: GRPCCore.RegistrableRPCService {
    func Store(
      request: GRPCCore.StreamingServerRequest<GRPCMessage<MyGame_Example_Stat>>,
      context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<GRPCMessage<MyGame_Example_Stat>>
    
    func Retrieve(
      request: GRPCCore.StreamingServerRequest<GRPCMessage<MyGame_Example_Monster>>,
      context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<GRPCMessage<MyGame_Example_Monster>>
    
    func GetMaxHitPoint(
      request: GRPCCore.StreamingServerRequest<GRPCMessage<MyGame_Example_Stat>>,
      context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<GRPCMessage<MyGame_Example_Stat>>
    
    func GetMinMaxHitPoints(
      request: GRPCCore.StreamingServerRequest<GRPCMessage<MyGame_Example_Stat>>,
      context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<GRPCMessage<MyGame_Example_Stat>>
    
  }
  
  public protocol ServiceProtocol: MyGame_Example_MonsterStorage.StreamingServiceProtocol {
    func Store(
      request: GRPCCore.ServerRequest<GRPCMessage<MyGame_Example_Stat>>,
      context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<GRPCMessage<MyGame_Example_Stat>>
    
    func Retrieve(
      request: GRPCCore.ServerRequest<GRPCMessage<MyGame_Example_Monster>>,
      context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<GRPCMessage<MyGame_Example_Monster>>
    
    func GetMaxHitPoint(
      request: GRPCCore.StreamingServerRequest<GRPCMessage<MyGame_Example_Stat>>,
      context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<GRPCMessage<MyGame_Example_Stat>>
    
    func GetMinMaxHitPoints(
      request: GRPCCore.StreamingServerRequest<GRPCMessage<MyGame_Example_Stat>>,
      context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<GRPCMessage<MyGame_Example_Stat>>
    
  }
}

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension MyGame_Example_MonsterStorage.StreamingServiceProtocol {
  public func registerMethods<Transport>(with router: inout GRPCCore.RPCRouter<Transport>) where Transport: GRPCCore.ServerTransport {
    router.registerHandler(
      forMethod: MyGame_Example_MonsterStorage.Method.Store.descriptor,
      deserializer: FlatBuffersMessageDeserializer<GRPCMessage<MyGame_Example_Stat>>(),
      serializer: FlatBuffersMessageSerializer<GRPCMessage<MyGame_Example_Stat>>(),
      handler: { request, context in
        try await self.Store(
          request: request,
          context: context
        )
      }
    )
    router.registerHandler(
      forMethod: MyGame_Example_MonsterStorage.Method.Retrieve.descriptor,
      deserializer: FlatBuffersMessageDeserializer<GRPCMessage<MyGame_Example_Monster>>(),
      serializer: FlatBuffersMessageSerializer<GRPCMessage<MyGame_Example_Monster>>(),
      handler: { request, context in
        try await self.Retrieve(
          request: request,
          context: context
        )
      }
    )
    router.registerHandler(
      forMethod: MyGame_Example_MonsterStorage.Method.GetMaxHitPoint.descriptor,
      deserializer: FlatBuffersMessageDeserializer<GRPCMessage<MyGame_Example_Stat>>(),
      serializer: FlatBuffersMessageSerializer<GRPCMessage<MyGame_Example_Stat>>(),
      handler: { request, context in
        try await self.GetMaxHitPoint(
          request: request,
          context: context
        )
      }
    )
    router.registerHandler(
      forMethod: MyGame_Example_MonsterStorage.Method.GetMinMaxHitPoints.descriptor,
      deserializer: FlatBuffersMessageDeserializer<GRPCMessage<MyGame_Example_Stat>>(),
      serializer: FlatBuffersMessageSerializer<GRPCMessage<MyGame_Example_Stat>>(),
      handler: { request, context in
        try await self.GetMinMaxHitPoints(
          request: request,
          context: context
        )
      }
    )
  }
}

#endif

