// Generated GRPC code for FlatBuffers swift!
/// The following code is generated by the Flatbuffers library which might not be in sync with grpc-swift
/// in case of an issue please open github issue, though it would be maintained

// swiftlint:disable all
// swiftformat:disable all

#if !os(Windows)
import FlatBuffers
import Foundation
import GRPCCore


/// Usage: instantiate models.GreeterServiceClient, then call methods of this protocol to make API calls.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension FlatBuffersMessageSerializer: MessageSerializer {
  public func serialize<Bytes>(_ message: Message) throws -> Bytes where Bytes : GRPCCore.GRPCContiguousBytes {
    do {
      return try self.serialize(message: message) as! Bytes
    } catch let error {
      throw RPCError(
        code: .invalidArgument,
        message: "Can't serialize message",
        cause: error
      )
    }
  }
}

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension FlatBuffersMessageDeserializer: MessageDeserializer {
  public func deserialize<Bytes>(_ serializedMessageBytes: Bytes) throws -> Message where Bytes : GRPCCore.GRPCContiguousBytes {
    do {
      return try serializedMessageBytes.withUnsafeBytes {
        try self.deserialize(pointer: $0)
      }
    } catch let error {
      throw RPCError(
        code: .invalidArgument,
        message: "Can't Decode message of type \(Message.self)",
        cause: error
      )
    }
  }
}
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
public enum models_Greeter: Sendable {
  public static let descriptor = GRPCCore.ServiceDescriptor(fullyQualifiedService: "models.Greeter")
  public enum Method: Sendable {
    public enum SayHello: Sendable {
      public typealias Input = FlatBufferBuilder
      public typealias Output = models_HelloReply
      public static let descriptor = GRPCCore.MethodDescriptor(
        service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "models.Greeter"),
        method: "SayHello"
      )
    }
    public enum SayManyHellos: Sendable {
      public typealias Input = FlatBufferBuilder
      public typealias Output = models_HelloReply
      public static let descriptor = GRPCCore.MethodDescriptor(
        service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "models.Greeter"),
        method: "SayManyHellos"
      )
    }
    public static let descriptors: [GRPCCore.MethodDescriptor] = [
      SayHello.descriptor,
      SayManyHellos.descriptor,
    ]
  }
}

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension GRPCCore.ServiceDescriptor {
  public static let models_Greeter = GRPCCore.ServiceDescriptor(fullyQualifiedService: "models.Greeter")
}

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension models_Greeter {
  public protocol StreamingServiceProtocol: GRPCCore.RegistrableRPCService {
    func SayHello(
      request: GRPCCore.StreamingServerRequest<GRPCMessage<models_HelloReply>>,
      context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<GRPCMessage<models_HelloReply>>
    
    func SayManyHellos(
      request: GRPCCore.StreamingServerRequest<GRPCMessage<models_HelloReply>>,
      context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<GRPCMessage<models_HelloReply>>
    
  }
  
  public protocol ServiceProtocol: models_Greeter.StreamingServiceProtocol {
    func SayHello(
      request: GRPCCore.ServerRequest<GRPCMessage<models_HelloReply>>,
      context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<GRPCMessage<models_HelloReply>>
    
    func SayManyHellos(
      request: GRPCCore.ServerRequest<GRPCMessage<models_HelloReply>>,
      context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<GRPCMessage<models_HelloReply>>
    
  }
}

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension models_Greeter.StreamingServiceProtocol {
  public func registerMethods<Transport>(with router: inout GRPCCore.RPCRouter<Transport>) where Transport: GRPCCore.ServerTransport {
    router.registerHandler(
      forMethod: models_Greeter.Method.SayHello.descriptor,
      deserializer: FlatBuffersMessageDeserializer<GRPCMessage<models_HelloReply>>(),
      serializer: FlatBuffersMessageSerializer<GRPCMessage<models_HelloReply>>(),
      handler: { request, context in
        try await self.SayHello(
          request: request,
          context: context
        )
      }
    )
    router.registerHandler(
      forMethod: models_Greeter.Method.SayManyHellos.descriptor,
      deserializer: FlatBuffersMessageDeserializer<GRPCMessage<models_HelloReply>>(),
      serializer: FlatBuffersMessageSerializer<GRPCMessage<models_HelloReply>>(),
      handler: { request, context in
        try await self.SayManyHellos(
          request: request,
          context: context
        )
      }
    )
  }
}

#endif

